title: Ajit Shinde
logo: /assets/img/2021-08-14 16.22.31.jpg
description: 
<a href="https://www.linkedin.com/in/ajit-shinde-49975662/">LinkedIn</a> |
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
